config/routes.rb
Meetruby::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  
  match 'work' => 'work_items#index'

  resources :inquiry_choices

  resources :inquiries

  resources :prices

  resources :feeds

  resources :venues

  resources :topics do 
    resources :labels
  end

  resources :events
  resources :books do
    collection do
      get :find
      post :import_from_google
    end
  end
  resources :conferences
  resources :videos
  resources :posts
  
  
  resources :sources 

  resources :profiles do
    resources :skills
  end

  resources :work_items
  

  root :to => "sources#index"

end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :source
  belongs_to :topic
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # GET /labels
  # GET /labels.xml
  def index
    @labels = Label.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @labels }
    end
  end

  # GET /labels/1
  # GET /labels/1.xml
  def show
    @label = Label.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @label }
    end
  end

  # GET /labels/new
  # GET /labels/new.xml
  def new
    @label = Label.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @label }
    end
  end

  # GET /labels/1/edit
  def edit
    @label = Label.find(params[:id])
  end

  # POST /labels
  # POST /labels.xml
  def create
    @label = Label.new(params[:label])

    respond_to do |format|
      if @label.save
        format.html { redirect_to(@label, :notice => 'Label was successfully created.') }
        format.xml  { render :xml => @label, :status => :created, :location => @label }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @label.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /labels/1
  # PUT /labels/1.xml
  def update
    @label = Label.find(params[:id])

    respond_to do |format|
      if @label.update_attributes(params[:label])
        format.html { redirect_to(@label, :notice => 'Label was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @label.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.xml
  def destroy
    @label = Label.find(params[:id])
    @label.destroy

    respond_to do |format|
      format.html { redirect_to(labels_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>
    <ul>
    <% @label.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  
  <div class="field">
    <%= f.label :ranking %><br />
    <%= f.text_field :ranking %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<h1>Listing labels</h1>

<table>
  <tr>
    <th>Topic</th>
    <th>Ranking</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labels.each do |label| %>
  <tr>
    <td><%= label.topic %></td>
    <td><%= label.ranking %></td>
    <td><%= link_to 'Show', label %></td>
    <td><%= link_to 'Edit', edit_label_path(label) %></td>
    <td><%= link_to 'Destroy', label, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @label.topic %>
</p>

<p>
  <b>Ranking:</b>
  <%= @label.ranking %>
</p>


<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>