config/routes.rb
Meetruby::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  
  match 'work' => 'work_items#index'

  resources :inquiry_choices

  resources :inquiries

  resources :prices

  resources :feeds

  resources :venues

  resources :topics do 
    resources :labels
  end

  resources :events
  resources :books do
    collection do
      get :find
      post :import_from_google
    end
  end
  resources :conferences
  resources :videos
  resources :posts
  
  
  resources :sources 

  resources :profiles do
    resources :skills
  end

  resources :work_items
  

  root :to => "sources#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :source, :as => :resourceful
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "tiny_mce/tiny_mce.js" %>
  
  
  <script type="text/javascript">
		tinyMCE.init({
			// General options
			mode : "textareas",
			theme : "advanced",
			plugins : "safari,advlink,paste",
			
			
				theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,paste,|,bullist,numlist,|,outdent,indent,|,undo,redo",
				
				theme_advanced_buttons2 : "",
  			theme_advanced_toolbar_location : "top",
  			theme_advanced_toolbar_align : "left",
  			theme_advanced_statusbar_location : "bottom",
  			theme_advanced_resizing : true,
  			width : 600,
  			height: 400
  		});
  		
  		
  			</script>
  			<% end %>
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
    <div id="errorExplanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> 
        prohibited this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title.blank? ? '' : post.title.html_safe  %></td>
    <td><%= post.author.html_safe %></td>
    <td><%= link_to 'Show', post.source.resourceful %></td>
    <td><%= link_to 'Edit', edit_source_path(post.source) %></td>
    <td><%= link_to 'Destroy', post.source, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Source', new_source_path %>

app/views/posts/new.html.erb
<div id="inner-content" class="content-scroll">

  <h1>New Entry</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
  
</div>

app/views/posts/show.html.erb
  


<div id="inner-content" class="content-scroll">
<p class="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title.blank? ? '' : @post.title.html_safe %>
</p>

<p>
  <b>Body:</b>
  <%= @post.content.html_safe %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>